### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by mastercoms** [Hypnootize/TF2-HUDs-Archive#27]
## comfig huds

huehued - https://comfig.app/huds/page/huehued/
LackHUD - https://comfig.app/huds/page/lackhud/
Mini Hud - https://comfig.app/huds/page/mini-hud/
srshud - https://comfig.app/huds/page/srshud/
Yahud Fragvid - https://comfig.app/huds/page/yahud-fragvid/

## github

SventooHUD - https://github.com/titO-2/SventooHUD

**Comment by Hypnootize** [comment]
Added them, thanks!
